/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicContainer: typeof import('./components/basic-container/index.vue')['default']
    README: typeof import('./components/sumile-table/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./components/search-panel/index.vue')['default']
    SumileOperatorList: typeof import('./components/sumile-operator-list/index.vue')['default']
    SumilePageLayout: typeof import('./components/sumile-page-layout/index.vue')['default']
    SumilePagination: typeof import('./components/sumile-pagination/index.vue')['default']
    SumileStatusColumn: typeof import('./components/sumile-status-column/index.vue')['default']
    SumileTable: typeof import('./components/sumile-table/index.vue')['default']
    SumileTree: typeof import('./components/sumile-tree/index.vue')['default']
  }
}
